### ISSUE TITLE
preselect most-frequent default values

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#12]
e.g. intentional for the repoducability field

In practice most researchers creating a virtual collection want to provide something reproducable. Would be good to give them a safe default.

**Comment by WillemElbers** [comment]
With the current beta an attempt has been made to preselect sensible defaults,  with indeed "intended" as the default for the reproducibility field.

Currently this is difficult to test, since authentication is broken.

I propose to do a review of all defaults after deploying the next release (and fixing authentication).

**Comment by WillemElbers** [comment]
Another additions that fit in here are:

* Use the authenticated user to add as a creator
* Use existing creators to easily add / autocomplete

**Comment by WillemElbers** [comment]
https://github.com/clarin-eric/VirtualCollectionRegistry/commit/7298517cb3dcd9cef8e86ea3007d18749a2bb86a
