### ISSUE TITLE
The submission endpoint throws a 500 error for (all?) incoming requests

### ISSUE THREAD

**Issue by zozlak** [clarin-eric/VirtualCollectionRegistry#151]
Trying to run the [sample request](https://github.com/clarin-eric/VirtualCollectionRegistry/blob/master/doc/Integration.md#examples) from the integration documentation against both http://collections.clarin-dev.eu/submit/extensional and http://collections.clarin.eu/submit/extensional throws an HTTP 500 error.

* (like in the docs against dev instance) `curl -v -u 'myClarinLogin:myClarinPswd' -d 'name=test&metadataUri=http://www.clarin.eu/1&metadataUri=http://www.clarin.eu/2&resourceUri=http://www.clarin.eu/&description=test-collection&keyword=&purpose=&reproducibility=' https://collections.clarin-dev.eu/submit/extensional`
* (like in the docs against prod instance) `curl -v -d 'name=test&metadataUri=http://www.clarin.eu/1&metadataUri=http://www.clarin.eu/2&resourceUri=http://www.clarin.eu/&description=test-collection&keyword=&purpose=&reproducibility=' https://collections.clarin-dev.eu/submit/extensional`

By the way tt doesn't matter if HTTP basic credentials are provided or not (I assume I proper response for the lack of authorization data would be HTTP 401 or 403 and not 500). Playing around with parameters being passed (e.g. removing ones not required according to [the docs](https://github.com/clarin-eric/VirtualCollectionRegistry/blob/master/doc/Integration.md#integration) or trying only with a single metadataUri/resourceUri pair) doesn't change the outcome as well:

* (without auth header against dev instance) `curl -v -d 'name=test&metadataUri=http://www.clarin.eu/1&metadataUri=http://www.clarin.eu/2&resourceUri=http://www.clarin.eu/&description=test-collection&keyword=&purpose=&reproducibility=' https://collections.clarin-dev.eu/submit/extensional`
* (without auth header against prod instance) `curl -v -d 'name=test&metadataUri=http://www.clarin.eu/1&metadataUri=http://www.clarin.eu/2&resourceUri=http://www.clarin.eu/&description=test-collection&keyword=&purpose=&reproducibility=' https://collections.clarin.eu/submit/extensional`
* (minimal set of parameters against dev instance) `curl -v -d 'name=test&description=test-collection&metadataUri=http://www.clarin.eu/1&resourceUri=http://www.clarin.eu/' https://collections.clarin-dev.eu/submit/extensional`
* (minimal set of parameters against prod instance) `curl -v -d 'name=test&description=test-collection&metadataUri=http://www.clarin.eu/1&resourceUri=http://www.clarin.eu/' https://collections.clarin.eu/submit/extensional`

**Comment by WillemElbers** [comment]
Unfortunately the curl example from the documentation only works against an instance with basic authentication. Neither the production nor dev instance have basic authentication available. Both are behind SAML authentication.

Testing agains these instances should be done using the suggested form based approach.

However, sending these request should indeed return a proper HTTP 401 or 403 response and not a HTTP 500. Also, since we have token based authentication support for the rest of the API it only makes sense to allow token based authentication for this endpoint as well.

**Comment by zozlak** [comment]
Sure, I used curl just because it was in the documentation and because it's easier to both write (when reporting an issue) and copy-paste (when trying to reproduce) a curl command that to provide/follow a description of the GUI interactions.

It doesn't change the fact that the properly handled curl request should return 401/403 or a 3xx redirecting to the authentication page and it does return 500.

If you prefer a GUI example of the error, you can use an HTML form below. I would expect it redirects me to the authentication service or return an error that I'm not authenticated but I'm getting an HTTP 500 instead.

```html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
    <form action="https://collections.clarin-dev.eu/submit/extensional" method="POST">
        name <input type="text" name="name" value="foo"/><br/>
        desc <input type="text" name="description" value="bar"/><br/>
        meta <input type="text" name="metadataUri" value="http://www.clarin.eu/2"/><br/>
        resr <input type="text" name="resourceUri" value="http://www.clarin.eu/"/><br/>
        <input type="submit" value="submit"/>
    </form>
    </form>
</body>
</html>
```

**Comment by WillemElbers** [comment]
The issue was caused through the introduction of a new feature in the latest release. We are storing the referrer header when collections are submitted. This failed when no referrer was available (the case with the curl example).

The beta instance (collections.clarin-dev.eu) has been updated and requests with no referrer are not returning HTTP 500 anymore.  The curl example is now returning a HTTP 302 response with a redirect to the UI.  To continue the workflow interaction with the UI is required. This will take care of authentication and allow to make updates to the collection before actually creating it.

Since the curl examples in the documentation are not really functional, I will remove these from the documentation.

**Comment by WillemElbers** [comment]
Via the API documentation (https://collections.clarin-dev.eu/service/) you can find a working example form as well: https://collections.clarin-dev.eu/test_vc_submission_extensional.html

**Comment by zozlak** [comment]
Thanks, it works now!

**Comment by zozlak** [comment]
It looks like the most recent dev instance updates reverted the fix:

* works (returns 302 redirect) `curl -i 'https://collections.clarin-dev.eu/submit/extensional' --data-binary 'name=ArcheCollection&resrouceUri=https%3A%2F%2Farche-dev.acdh-dev.oeaw.ac.at%2Fapi%2F8956%2F' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Referer: https://arche-dev.acdh-dev.oeaw.ac.at/'`
* doesn't work (returns 500 - Java NullPointerException) - `curl -i 'https://collections.clarin-dev.eu/submit/extensional' --data-binary 'name=ArcheCollection&resrouceUri=https%3A%2F%2Farche-dev.acdh-dev.oeaw.ac.at%2Fapi%2F8956%2F' -H 'Content-Type: application/x-www-form-urlencoded'`

The only difference is the lack of the `Referer` request header in the second request.

**Comment by WillemElbers** [comment]
Correct, the latest update on the dev instance introduced another issue that prevented collections from being inserted / updated. I did a rollback to v1.6.1 which indeed reverted the fix for this issue. 

With the increased usage of the beta instance (collections.clarin-dev.eu) we are looking into deploying a third development instance with higher priority. This should provide a more stable beta environment for testing by external parties.

**Comment by zozlak** [comment]
> With the increased usage of the beta instance (collections.clarin-dev.eu) we are looking into deploying a third development instance with higher priority. This should provide a more stable beta environment for testing by external parties.

It will be helpful.

> Correct, the latest update on the dev instance introduced another issue that prevented collections from being inserted / updated. I did a rollback to v1.6.1 which indeed reverted the fix for this issue.

I know it's a complex topic, mainly because of the authentication, but maybe it would be good to set up some automatic tests for checking the ingestion endpoint workflow?

**Comment by zozlak** [comment]
I can help with the client side test code but I would need a CI code deploying the VCR using e.g. github actions so there is something to test against.

**Comment by zozlak** [comment]
Resolved by the version available under https://beta-collections.clarin.eu
